server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      # UWAGA: create-drop kasuje dane przy każdym restarcie aplikacji!
      # Jeśli chcesz zachować dane, zmień na 'update'.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true