server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

huggingface:
  api-url: https://router.huggingface.co/v1/chat/completions
  api-token: ${HUGGINGFACE_API_TOKEN}
  model: HuggingFaceTB/SmolLM3-3B:hf-inference
  max-tokens: 150
  temperature: 0.7
  system-prompt: "/no_think\nJesteś nauczycielem angielskiego. Odpowiadaj krótko i jasno."
